Added some error checking

diff --git a/update_instance b/update_instance
--- a/update_instance
+++ b/update_instance
@@ -1,8 +1,8 @@
 #!/bin/sh
 
 ## define paths
-export frontend_path=/opt/lqfb/frontend/2.1.0
-export core_path=/opt/lqfb/core/2.0.12
+export frontend_path=/opt/lqfb/frontend/2.1.2
+export core_path=/opt/lqfb/core/2.1.0
 export webmcp_path=/opt/lqfb/webmcp/1.2.5
 export update_base=$core_path/update/
 
@@ -41,6 +41,12 @@ then
         exit 1
 fi
 
+if ! [[ "$awnser" =~ ^[0-9]+$ ]] || [ $awnser -gt $lineNum ]
+then
+	echo "Invalid awnser"
+	exit 1
+fi
+
 export instance=($(sed -n "${awnser}p" /opt/lqfb/instances))
 
 # copy config file
@@ -74,7 +80,7 @@ EOF
 
 #copy database
 export db_name=${instance[1]}
-su www-data --preserve-environment -c 'echo CREATE DATABASE ${db_name}_11 WITH TEMPLATE $db_name | psql $db_name' 
+#su www-data --preserve-environment -c 'echo CREATE DATABASE ${db_name}_11 WITH TEMPLATE $db_name | psql $db_name' 
 
 #update database
 cd $update_base
